# Generated by Django 4.1.13 on 2023-12-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0003_log"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("endpoint", models.CharField(max_length=255)),
                ("ip_address", models.GenericIPAddressField()),
                ("status", models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="Log",
        ),
    ]
